apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  #namespace: larapgsql
spec:
  selector:
    matchLabels:
      app: pgadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin4
        image: fenglc/pgadmin4
        resources:
          limits:
            memory: "128Mi"
            cpu: "150m"
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "pgadmin4@pgadmin.org"
        - name: PGADMIN_DEFAULT_PASSWORD
          value: "admin"
        - name: PGADMIN_PORT
          value: "5050"
        ports:
        - containerPort: 5050
          name: pgadmin

---

apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  #namespace: larapgsql
  labels:
    app: pgadmin
spec:
  type: NodePort
  selector:
    app: pgadmin
  ports:
  - port: 5050
    targetPort: 5050
    nodePort: 30200