apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume
  labels:
    type: local
    app: postgres
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  claimRef:
    namespace: default
    name: postgres-pv-claim
  nfs:
    server: 172.31.218.120
    path: "/srv/nfs/db_dataku/"
  persistentVolumeReclaimPolicy: Retain